#!/usr/bin/env node

const fs = require('fs/promises');
const path = require('path');

const cookbookRoot = path.resolve(__dirname, '..');
const outputFile = path.join(cookbookRoot, 'llm.txt');
const includeExtensions = new Set(['.md', '.mdx']);
const ignoredDirs = new Set([
  '.git',
  '.docusaurus',
  '.idea',
  '.cache',
  'node_modules',
  'build'
]);

async function collectMarkdownFiles(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (ignoredDirs.has(entry.name)) continue;
      files.push(...(await collectMarkdownFiles(fullPath)));
    } else if (entry.isFile()) {
      const ext = path.extname(entry.name).toLowerCase();
      if (includeExtensions.has(ext)) {
        files.push(fullPath);
      }
    }
  }

  return files;
}

function normalizePath(p) {
  return p.replace(/\\/g, '/');
}

async function main() {
  const markdownFiles = await collectMarkdownFiles(cookbookRoot);
  const sorted = markdownFiles.sort((a, b) => {
    const relA = normalizePath(path.relative(cookbookRoot, a));
    const relB = normalizePath(path.relative(cookbookRoot, b));
    return relA.localeCompare(relB);
  });

  const sections = [];
  for (const file of sorted) {
    const relativePath = normalizePath(path.relative(cookbookRoot, file));
    if (relativePath === 'llm.txt') continue; // avoid self-inclusion

    const content = await fs.readFile(file, 'utf8');
    const trimmed = content.trim();
    sections.push(`FILE: ${relativePath}\n\n${trimmed}\n`);
  }

  const header =
    'SpoonOS Cookbook – Combined Markdown Export\n' +
    'Generated by cookbook/scripts/generate-llm.js\n';

  const body = sections.join('\n---\n\n');
  await fs.writeFile(outputFile, `${header}\n---\n\n${body}\n`, 'utf8');
  console.log(`Wrote ${outputFile} from ${sections.length} files.`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
